In [1]:
import pandas as pd
from sklearn import metrics
import numpy as np
import itertools
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('fake_or_real_news.csv')
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [3]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6335 non-null   int64 
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [5]:
df.label.replace({"FAKE":0 ,"REAL":0 }, inplace = True)

In [6]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  label  
0  Daniel Greenfield, a Shillman Journalism Fello...      0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...      0  
2  U.S. Secretary of State John F. Kerry said Mon...      0  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...      0  
4  It's primary day in New York and front-runners...      0

In [7]:
x=df.drop('label',axis=1)
x.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  
0  Daniel Greenfield, a Shillman Journalism Fello...  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  
2  U.S. Secretary of State John F. Kerry said Mon...  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4  It's primary day in New York and front-runners...

In [8]:
y=df['label']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [9]:
df.shape

(6335, 4)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [11]:
messages=df.copy()

In [12]:
messages['title'][6]

'Girl Horrified At What She Watches Boyfriend Do After He Left FaceTime On'

In [13]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [14]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [15]:
corpus[3]

'berni support twitter erupt anger dnc tri warn'

# CountVectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))  #take the most  5000 frequently occuring words and use 1-3 words to make a feature
x = cv.fit_transform(corpus).toarray()

In [17]:
x.shape

(6335, 5000)

In [18]:
y=messages['label']

In [19]:
y.shape

(6335,)

In [21]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
y

0       0
1       0
2       0
3       0
4       0
       ..
6330    0
6331    0
6332    0
6333    0
6334    0
Name: label, Length: 6335, dtype: int64

In [23]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=88)

In [24]:
cv.get_feature_names()

['abandon',
 'abc',
 'abc news',
 'abdullah',
 'abedin',
 'abedin weiner',
 'abedin weiner laptop',
 'abil',
 'aboard',
 'abolish',
 'abort',
 'abort answer',
 'absolut',
 'abstain',
 'abstain un',
 'abstain un vote',
 'absurd',
 'abus',
 'abus power',
 'accept',
 'accept elect',
 'accept elect result',
 'accept foreign',
 'access',
 'access pipelin',
 'accid',
 'accident',
 'accord',
 'account',
 'accus',
 'accus trump',
 'achiev',
 'acknowledg',
 'acquit',
 'acquit malheur',
 'acquit malheur wildlif',
 'acquitt',
 'acr',
 'across',
 'across countri',
 'across us',
 'act',
 'act like',
 'action',
 'activ',
 'activist',
 'actual',
 'ad',
 'ad job',
 'add',
 'addict',
 'address',
 'adhd',
 'admin',
 'administr',
 'admir',
 'admit',
 'admit zika',
 'adult',
 'advanc',
 'advanc mosul',
 'advantag',
 'advert',
 'advertis',
 'advis',
 'advoc',
 'affair',
 'affect',
 'affili',
 'afford',
 'afghan',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'african american',
 'ag',
 'ag lynch',
 'a

In [25]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [26]:
count_df = pd.DataFrame(x_train, columns=cv.get_feature_names())
count_df.head(20)

abandon  abc  abc news  abdullah  abedin  abedin weiner  \
0         0    0         0         0       0              0   
1         0    0         0         0       0              0   
2         0    0         0         0       0              0   
3         0    0         0         0       0              0   
4         0    0         0         0       0              0   
5         0    0         0         0       0              0   
6         0    0         0         0       0              0   
7         0    0         0         0       0              0   
8         0    0         0         0       0              0   
9         0    0         0         0       0              0   
10        0    0         0         0       0              0   
11        0    0         0         0       0              0   
12        0    0         0         0       0              0   
13        0    0         0         0       0              0   
14        0    0         0         0       0              0   
15        0    0         0         0       0              0   
16        0    0         0         0       0              0   
17        0    0         0         0       0              0   
18        0    0         0         0       0              0   
19        0    0         0         0       0              0   

    abedin weiner laptop  abil  aboard  abolish  ...  zika scaremong  \
0                      0     0       0        0  ...               0   
1                      0     0       0        0  ...               0   
2                      0     0       0        0  ...               0   
3                      0     0       0        0  ...               0   
4                      0     0       0        0  ...               0   
5                      0     0       0        0  ...               0   
6                      0     0       0        0  ...               0   
7                      0     0       0        0  ...               0   
8                      0     0       0        0  ...               0   
9                      0     0       0        0  ...               0   
10                     0     0       0        0  ...               0   
11                     0     0       0        0  ...               0   
12                     0     0       0        0  ...               0   
13                     0     0       0        0  ...               0   
14                     0     0       0        0  ...               0   
15                     0     0       0        0  ...               0   
16                     0     0       0        0  ...               0   
17                     0     0       0        0  ...               0   
18                     0     0       0        0  ...               0   
19                     0     0       0        0  ...               0   

    zika scaremong washington  zika viru  zika viru caus  zika viru harmless  \
0                           0          0               0                   0   
1                           0          0               0                   0   
2                           0          0               0                   0   
3                           0          0               0                   0   
4                           0          0               0                   0   
5                           0          0               0                   0   
6                           0          0               0                   0   
7                           0          0               0                   0   
8                           0          0               0                   0   
9                           0          0               0                   0   
10                          0          0               0                   0   
11                          0          0               0                   0   
12                          0          0               0                   0   
13                          0          0       

In [27]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(5068, 5000)
(5068,)
(1267, 5000)
(1267,)


### Naive Bayes

In [28]:
from sklearn.naive_bayes import MultinomialNB
nbc=MultinomialNB()
nbc.fit(x_train, y_train)
pred = nbc.predict(x_test)
tab1=confusion_matrix(pred,y_test)
tab1

array([[1267]], dtype=int64)

In [29]:
acc=tab1.diagonal().sum()* 100 / tab1.sum()
acc

100.0

In [30]:
feature_names = cv.get_feature_names()
sorted(zip(nbc.coef_[0], feature_names))[:]

C:\Users\shree\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[(-10.725203833890781, 'abus power'),
 (-10.725203833890781, 'blind'),
 (-10.725203833890781, 'block testimoni'),
 (-10.725203833890781, 'block testimoni senior'),
 (-10.725203833890781, 'bonu'),
 (-10.725203833890781, 'brawl'),
 (-10.725203833890781, 'cabl'),
 (-10.725203833890781, 'campaign tri hack'),
 (-10.725203833890781, 'chang one'),
 (-10.725203833890781, 'check first'),
 (-10.725203833890781, 'check first clinton'),
 (-10.725203833890781, 'chemotherapi'),
 (-10.725203833890781, 'clinton person'),
 (-10.725203833890781, 'clinton person email'),
 (-10.725203833890781, 'clinton polici syria'),
 (-10.725203833890781, 'credit'),
 (-10.725203833890781, 'death threat'),
 (-10.725203833890781, 'democrat want berni'),
 (-10.725203833890781, 'director jame'),
 (-10.725203833890781, 'director jame comey'),
 (-10.725203833890781, 'discov messag'),
 (-10.725203833890781, 'discov messag sent'),
 (-10.725203833890781, 'four reason'),
 (-10.725203833890781, 'inch'),
 (-10.725203833890781, 'in

# TF-IDF

In [31]:
## TFidf Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000,ngram_range=(1,3)) ###
x=tfidf.fit_transform(corpus).toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [33]:
count_tfidf = pd.DataFrame(x_train, columns=tfidf.get_feature_names())
count_tfidf.head(20)

abandon  abc  abc news  abdullah  abedin  abedin weiner  \
0       0.0  0.0       0.0       0.0     0.0            0.0   
1       0.0  0.0       0.0       0.0     0.0            0.0   
2       0.0  0.0       0.0       0.0     0.0            0.0   
3       0.0  0.0       0.0       0.0     0.0            0.0   
4       0.0  0.0       0.0       0.0     0.0            0.0   
5       0.0  0.0       0.0       0.0     0.0            0.0   
6       0.0  0.0       0.0       0.0     0.0            0.0   
7       0.0  0.0       0.0       0.0     0.0            0.0   
8       0.0  0.0       0.0       0.0     0.0            0.0   
9       0.0  0.0       0.0       0.0     0.0            0.0   
10      0.0  0.0       0.0       0.0     0.0            0.0   
11      0.0  0.0       0.0       0.0     0.0            0.0   
12      0.0  0.0       0.0       0.0     0.0            0.0   
13      0.0  0.0       0.0       0.0     0.0            0.0   
14      0.0  0.0       0.0       0.0     0.0            0.0   
15      0.0  0.0       0.0       0.0     0.0            0.0   
16      0.0  0.0       0.0       0.0     0.0            0.0   
17      0.0  0.0       0.0       0.0     0.0            0.0   
18      0.0  0.0       0.0       0.0     0.0            0.0   
19      0.0  0.0       0.0       0.0     0.0            0.0   

    abedin weiner laptop  abil  aboard  abolish  ...  zika scaremong  \
0                    0.0   0.0     0.0      0.0  ...             0.0   
1                    0.0   0.0     0.0      0.0  ...             0.0   
2                    0.0   0.0     0.0      0.0  ...             0.0   
3                    0.0   0.0     0.0      0.0  ...             0.0   
4                    0.0   0.0     0.0      0.0  ...             0.0   
5                    0.0   0.0     0.0      0.0  ...             0.0   
6                    0.0   0.0     0.0      0.0  ...             0.0   
7                    0.0   0.0     0.0      0.0  ...             0.0   
8                    0.0   0.0     0.0      0.0  ...             0.0   
9                    0.0   0.0     0.0      0.0  ...             0.0   
10                   0.0   0.0     0.0      0.0  ...             0.0   
11                   0.0   0.0     0.0      0.0  ...             0.0   
12                   0.0   0.0     0.0      0.0  ...             0.0   
13                   0.0   0.0     0.0      0.0  ...             0.0   
14                   0.0   0.0     0.0      0.0  ...             0.0   
15                   0.0   0.0     0.0      0.0  ...             0.0   
16                   0.0   0.0     0.0      0.0  ...             0.0   
17                   0.0   0.0     0.0      0.0  ...             0.0   
18                   0.0   0.0     0.0      0.0  ...             0.0   
19                   0.0   0.0     0.0      0.0  ...             0.0   

    zika scaremong washington  zika viru  zika viru caus  zika viru harmless  \
0                         0.0        0.0             0.0                 0.0   
1                         0.0        0.0             0.0                 0.0   
2                         0.0        0.0             0.0                 0.0   
3                         0.0        0.0             0.0                 0.0   
4                         0.0        0.0             0.0                 0.0   
5                         0.0        0.0             0.0                 0.0   
6                         0.0        0.0             0.0                 0.0   
7                         0.0        0.0             0.0                 0.0   
8                         0.0        0.0             0.0                 0.0   
9                         0.0        0.0             0.0                 0.0   
10                        0.0        0.0             0.0                 0.0   
11                        0.0        0.0             0.0                 0.0   
12                        0.0        0.0             0.0                 0.0   
13                        0.0        0.0       

In [34]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(5068, 5000)
(5068,)
(1267, 5000)
(1267,)


In [35]:
from sklearn.naive_bayes import MultinomialNB
nbc=MultinomialNB()
nbc.fit(x_train, y_train)
pred2 = nbc.predict(x_test)
tab2=confusion_matrix(pred2,y_test)
tab2

array([[1267]], dtype=int64)

In [36]:
acc2=tab2.diagonal().sum()* 100 / tab2.sum()
acc2

100.0

In [37]:
feature_names2 = cv.get_feature_names()
sorted(zip(nbc.coef_[0], feature_names2))[:]

C:\Users\shree\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[(-9.828276348262591, 'blind'),
 (-9.828276348262591, 'block trump'),
 (-9.828276348262591, 'bold'),
 (-9.828276348262591, 'boyfriend'),
 (-9.828276348262591, 'brain tumor'),
 (-9.828276348262591, 'brain tumor associ'),
 (-9.828276348262591, 'cbn'),
 (-9.828276348262591, 'clinton foundat laughabl'),
 (-9.828276348262591, 'damn'),
 (-9.828276348262591, 'dead heat'),
 (-9.828276348262591, 'dead muslim'),
 (-9.828276348262591, 'debat video'),
 (-9.828276348262591, 'dilligaf'),
 (-9.828276348262591, 'disclos pricey'),
 (-9.828276348262591, 'disclos pricey present'),
 (-9.828276348262591, 'foundat laughabl'),
 (-9.828276348262591, 'foundat laughabl total'),
 (-9.828276348262591, 'friday'),
 (-9.828276348262591, 'ga price'),
 (-9.828276348262591, 'gift bill'),
 (-9.828276348262591, 'homeless man'),
 (-9.828276348262591, 'incom tax'),
 (-9.828276348262591, 'industri appeal'),
 (-9.828276348262591, 'industri appeal brain'),
 (-9.828276348262591, 'ipso'),
 (-9.828276348262591, 'ipso poll'),
 (-