In [1]:
import pandas as pd
from sklearn import metrics
import numpy as np
import itertools
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('fake_or_real_news.csv')
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [3]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6335 non-null   int64 
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [5]:
df.label.replace({"FAKE":0 ,"REAL":1}, inplace = True)

In [6]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  label  
0  Daniel Greenfield, a Shillman Journalism Fello...      0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...      0  
2  U.S. Secretary of State John F. Kerry said Mon...      1  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...      0  
4  It's primary day in New York and front-runners...      1

In [7]:
x=df.drop('label',axis=1)
x.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  
0  Daniel Greenfield, a Shillman Journalism Fello...  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  
2  U.S. Secretary of State John F. Kerry said Mon...  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4  It's primary day in New York and front-runners...

In [8]:
y=df['label']
y.head()

0    0
1    0
2    1
3    0
4    1
Name: label, dtype: int64

In [9]:
df.shape

(6335, 4)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [11]:
messages=df.copy()

In [12]:
messages['title'][6]

'Girl Horrified At What She Watches Boyfriend Do After He Left FaceTime On'

In [13]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [14]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [15]:
corpus[3]

'berni support twitter erupt anger dnc tri warn'

# CountVectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))  #take the most  5000 frequently occuring words and use 1-3 words to make a feature
x = cv.fit_transform(corpus).toarray()

In [17]:
x.shape

(6335, 5000)

In [18]:
y=messages['label']

In [19]:
y.shape

(6335,)

In [20]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
y

0       0
1       0
2       1
3       0
4       1
       ..
6330    1
6331    0
6332    0
6333    1
6334    1
Name: label, Length: 6335, dtype: int64

In [22]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=88)

In [23]:
cv.get_feature_names()

['abandon',
 'abc',
 'abc news',
 'abdullah',
 'abedin',
 'abedin weiner',
 'abedin weiner laptop',
 'abil',
 'aboard',
 'abolish',
 'abort',
 'abort answer',
 'absolut',
 'abstain',
 'abstain un',
 'abstain un vote',
 'absurd',
 'abus',
 'abus power',
 'accept',
 'accept elect',
 'accept elect result',
 'accept foreign',
 'access',
 'access pipelin',
 'accid',
 'accident',
 'accord',
 'account',
 'accus',
 'accus trump',
 'achiev',
 'acknowledg',
 'acquit',
 'acquit malheur',
 'acquit malheur wildlif',
 'acquitt',
 'acr',
 'across',
 'across countri',
 'across us',
 'act',
 'act like',
 'action',
 'activ',
 'activist',
 'actual',
 'ad',
 'ad job',
 'add',
 'addict',
 'address',
 'adhd',
 'admin',
 'administr',
 'admir',
 'admit',
 'admit zika',
 'adult',
 'advanc',
 'advanc mosul',
 'advantag',
 'advert',
 'advertis',
 'advis',
 'advoc',
 'affair',
 'affect',
 'affili',
 'afford',
 'afghan',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'african american',
 'ag',
 'ag lynch',
 'a

In [24]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [25]:
count_df = pd.DataFrame(x_train, columns=cv.get_feature_names())
count_df.head(20)

abandon  abc  abc news  abdullah  abedin  abedin weiner  \
0         0    0         0         0       0              0   
1         0    0         0         0       0              0   
2         0    0         0         0       0              0   
3         0    0         0         0       0              0   
4         0    0         0         0       0              0   
5         0    0         0         0       0              0   
6         0    0         0         0       0              0   
7         0    0         0         0       0              0   
8         0    0         0         0       0              0   
9         0    0         0         0       0              0   
10        0    0         0         0       0              0   
11        0    0         0         0       0              0   
12        0    0         0         0       0              0   
13        0    0         0         0       0              0   
14        0    0         0         0       0              0   
15        0    0         0         0       0              0   
16        0    0         0         0       0              0   
17        0    0         0         0       0              0   
18        0    0         0         0       0              0   
19        0    0         0         0       0              0   

    abedin weiner laptop  abil  aboard  abolish  ...  zika scaremong  \
0                      0     0       0        0  ...               0   
1                      0     0       0        0  ...               0   
2                      0     0       0        0  ...               0   
3                      0     0       0        0  ...               0   
4                      0     0       0        0  ...               0   
5                      0     0       0        0  ...               0   
6                      0     0       0        0  ...               0   
7                      0     0       0        0  ...               0   
8                      0     0       0        0  ...               0   
9                      0     0       0        0  ...               0   
10                     0     0       0        0  ...               0   
11                     0     0       0        0  ...               0   
12                     0     0       0        0  ...               0   
13                     0     0       0        0  ...               0   
14                     0     0       0        0  ...               0   
15                     0     0       0        0  ...               0   
16                     0     0       0        0  ...               0   
17                     0     0       0        0  ...               0   
18                     0     0       0        0  ...               0   
19                     0     0       0        0  ...               0   

    zika scaremong washington  zika viru  zika viru caus  zika viru harmless  \
0                           0          0               0                   0   
1                           0          0               0                   0   
2                           0          0               0                   0   
3                           0          0               0                   0   
4                           0          0               0                   0   
5                           0          0               0                   0   
6                           0          0               0                   0   
7                           0          0               0                   0   
8                           0          0               0                   0   
9                           0          0               0                   0   
10                          0          0               0                   0   
11                          0          0               0                   0   
12                          0          0               0                   0   
13                          0          0       

In [26]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(5068, 5000)
(5068,)
(1267, 5000)
(1267,)


### Naive Bayes

In [27]:
from sklearn.naive_bayes import MultinomialNB
nbc=MultinomialNB()
nbc.fit(x_train, y_train)
pred = nbc.predict(x_test)
tab1=confusion_matrix(pred,y_test)
tab1

array([[501, 112],
       [115, 539]], dtype=int64)

In [28]:
acc=tab1.diagonal().sum()* 100 / tab1.sum()
acc

82.08366219415943

In [29]:
feature_names = cv.get_feature_names()
sorted(zip(nbc.coef_[0], feature_names))[:]

C:\Users\shree\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[(-10.114720452824503, 'abc news'),
 (-10.114720452824503, 'abedin weiner'),
 (-10.114720452824503, 'abedin weiner laptop'),
 (-10.114720452824503, 'abil'),
 (-10.114720452824503, 'abstain'),
 (-10.114720452824503, 'abstain un'),
 (-10.114720452824503, 'abstain un vote'),
 (-10.114720452824503, 'abus power'),
 (-10.114720452824503, 'access pipelin'),
 (-10.114720452824503, 'achiev'),
 (-10.114720452824503, 'acquit'),
 (-10.114720452824503, 'acquit malheur'),
 (-10.114720452824503, 'acquit malheur wildlif'),
 (-10.114720452824503, 'acquitt'),
 (-10.114720452824503, 'across countri'),
 (-10.114720452824503, 'addict'),
 (-10.114720452824503, 'adhd'),
 (-10.114720452824503, 'admit zika'),
 (-10.114720452824503, 'advanc mosul'),
 (-10.114720452824503, 'advert'),
 (-10.114720452824503, 'advertis'),
 (-10.114720452824503, 'ag lynch'),
 (-10.114720452824503, 'ag lynch told'),
 (-10.114720452824503, 'airstrik kill'),
 (-10.114720452824503, 'airstrik yemen'),
 (-10.114720452824503, 'akbar'),
 (-

# TF-IDF

In [30]:
## TFidf Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000,ngram_range=(1,3)) ###
x=tfidf.fit_transform(corpus).toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [32]:
count_tfidf = pd.DataFrame(x_train, columns=tfidf.get_feature_names())
count_tfidf.head(20)

abandon  abc  abc news  abdullah  abedin  abedin weiner  \
0       0.0  0.0       0.0       0.0     0.0            0.0   
1       0.0  0.0       0.0       0.0     0.0            0.0   
2       0.0  0.0       0.0       0.0     0.0            0.0   
3       0.0  0.0       0.0       0.0     0.0            0.0   
4       0.0  0.0       0.0       0.0     0.0            0.0   
5       0.0  0.0       0.0       0.0     0.0            0.0   
6       0.0  0.0       0.0       0.0     0.0            0.0   
7       0.0  0.0       0.0       0.0     0.0            0.0   
8       0.0  0.0       0.0       0.0     0.0            0.0   
9       0.0  0.0       0.0       0.0     0.0            0.0   
10      0.0  0.0       0.0       0.0     0.0            0.0   
11      0.0  0.0       0.0       0.0     0.0            0.0   
12      0.0  0.0       0.0       0.0     0.0            0.0   
13      0.0  0.0       0.0       0.0     0.0            0.0   
14      0.0  0.0       0.0       0.0     0.0            0.0   
15      0.0  0.0       0.0       0.0     0.0            0.0   
16      0.0  0.0       0.0       0.0     0.0            0.0   
17      0.0  0.0       0.0       0.0     0.0            0.0   
18      0.0  0.0       0.0       0.0     0.0            0.0   
19      0.0  0.0       0.0       0.0     0.0            0.0   

    abedin weiner laptop  abil  aboard  abolish  ...  zika scaremong  \
0                    0.0   0.0     0.0      0.0  ...             0.0   
1                    0.0   0.0     0.0      0.0  ...             0.0   
2                    0.0   0.0     0.0      0.0  ...             0.0   
3                    0.0   0.0     0.0      0.0  ...             0.0   
4                    0.0   0.0     0.0      0.0  ...             0.0   
5                    0.0   0.0     0.0      0.0  ...             0.0   
6                    0.0   0.0     0.0      0.0  ...             0.0   
7                    0.0   0.0     0.0      0.0  ...             0.0   
8                    0.0   0.0     0.0      0.0  ...             0.0   
9                    0.0   0.0     0.0      0.0  ...             0.0   
10                   0.0   0.0     0.0      0.0  ...             0.0   
11                   0.0   0.0     0.0      0.0  ...             0.0   
12                   0.0   0.0     0.0      0.0  ...             0.0   
13                   0.0   0.0     0.0      0.0  ...             0.0   
14                   0.0   0.0     0.0      0.0  ...             0.0   
15                   0.0   0.0     0.0      0.0  ...             0.0   
16                   0.0   0.0     0.0      0.0  ...             0.0   
17                   0.0   0.0     0.0      0.0  ...             0.0   
18                   0.0   0.0     0.0      0.0  ...             0.0   
19                   0.0   0.0     0.0      0.0  ...             0.0   

    zika scaremong washington  zika viru  zika viru caus  zika viru harmless  \
0                         0.0        0.0             0.0                 0.0   
1                         0.0        0.0             0.0                 0.0   
2                         0.0        0.0             0.0                 0.0   
3                         0.0        0.0             0.0                 0.0   
4                         0.0        0.0             0.0                 0.0   
5                         0.0        0.0             0.0                 0.0   
6                         0.0        0.0             0.0                 0.0   
7                         0.0        0.0             0.0                 0.0   
8                         0.0        0.0             0.0                 0.0   
9                         0.0        0.0             0.0                 0.0   
10                        0.0        0.0             0.0                 0.0   
11                        0.0        0.0             0.0                 0.0   
12                        0.0        0.0             0.0                 0.0   
13                        0.0        0.0       

In [33]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(5068, 5000)
(5068,)
(1267, 5000)
(1267,)


In [34]:
from sklearn.naive_bayes import MultinomialNB
nbc=MultinomialNB()
nbc.fit(x_train, y_train)
pred2 = nbc.predict(x_test)
tab2=confusion_matrix(pred2,y_test)
tab2

array([[493,  98],
       [122, 554]], dtype=int64)

In [35]:
acc2=tab2.diagonal().sum()* 100 / tab2.sum()
acc2

82.63614838200473

In [36]:
feature_names2 = cv.get_feature_names()
sorted(zip(nbc.coef_[0], feature_names2))[:]

C:\Users\shree\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[(-9.368150458681047, 'abc news'),
 (-9.368150458681047, 'abedin'),
 (-9.368150458681047, 'abedin weiner'),
 (-9.368150458681047, 'abedin weiner laptop'),
 (-9.368150458681047, 'abil'),
 (-9.368150458681047, 'abstain'),
 (-9.368150458681047, 'abstain un'),
 (-9.368150458681047, 'abstain un vote'),
 (-9.368150458681047, 'accept foreign'),
 (-9.368150458681047, 'access pipelin'),
 (-9.368150458681047, 'achiev'),
 (-9.368150458681047, 'acquit'),
 (-9.368150458681047, 'acquit malheur'),
 (-9.368150458681047, 'acquit malheur wildlif'),
 (-9.368150458681047, 'acquitt'),
 (-9.368150458681047, 'across countri'),
 (-9.368150458681047, 'addict'),
 (-9.368150458681047, 'adhd'),
 (-9.368150458681047, 'admit zika'),
 (-9.368150458681047, 'advanc mosul'),
 (-9.368150458681047, 'advert'),
 (-9.368150458681047, 'advertis'),
 (-9.368150458681047, 'ag lynch'),
 (-9.368150458681047, 'ag lynch told'),
 (-9.368150458681047, 'agent'),
 (-9.368150458681047, 'air'),
 (-9.368150458681047, 'airstrik yemen'),
 (

### LSTM

In [1]:
import pandas as pd
df=pd.read_csv('fake_or_real_news.csv')

In [2]:
import tensorflow as tf
import keras as k
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences 
#bcoz we want to process the data in seuence in embedding & Input of fixed size and equal in length.

from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

C:\Users\shree\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\shree\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\shree\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\shree\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [3]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [4]:
###Drop Nan Values
df=df.dropna()

In [5]:
X=df.drop('label',axis=1)

In [6]:
y=df['label']

In [7]:
print(X.shape)
print(y.shape)

(6335, 3)
(6335,)


In [8]:
### Vocabulary size
voc_size=5000

### One Hot Representation

In [9]:
messages=X.copy()  #copying the data of X in messages

In [10]:
messages['title'][1]

'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)'

In [11]:
df.label.replace({"FAKE":0 ,"REAL":1}, inplace = True)

In [12]:
messages.reset_index(inplace=True)  #using reset index bcoz we have dropped null values above

In [13]:
import nltk
import re
from nltk.corpus import stopwords

In [14]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer  #for stemming
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])  #substituting every charcter except [^a-zA-Z] wid blank on title of every messages
    review = review.lower() #making evevrything to lowercase
    review = review.split() #splitting
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')] #stem the words only if they are not in stopwords
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064


3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719


5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191
5192
5193
5194
5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361


In [15]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4718, 1271, 3966],
 [559, 964, 4841, 4110, 2270, 2260, 2382, 2669, 3787, 252, 4440],
 [1414, 3535, 4967, 3191, 511],
 [3747, 1628, 4823, 3505, 3922, 2345, 3621, 2478],
 [2343, 4579, 3668, 1806, 1792],
 [94, 1740],
 [2250, 1286, 559, 1819, 4602, 4479],
 [1506, 632, 3779],
 [4616, 2713, 3787, 1904, 4340, 265, 885],
 [3552, 3442, 2543, 4579, 3490, 48, 975, 1355, 7],
 [2104, 1904, 2598, 4664, 4241, 1565, 1271, 1904, 4371],
 [3824, 3787, 3600, 3774, 2178, 2340, 2925, 2439, 878, 3194],
 [624, 86, 1016, 2064, 2628, 1756, 1691, 2972, 4440],
 [18, 1558, 3278, 4570, 4983],
 [3787, 194, 4317, 2728],
 [2808, 4535, 4957],
 [4480, 235, 2618, 1271, 1567, 556, 3391, 3896, 3330],
 [1271, 1904, 2207, 1539, 1558, 2063, 2938, 3140, 3398, 418, 4559, 1756, 1691],
 [3552, 1980, 2618, 2284],
 [4660, 2719, 2610, 1183, 2067, 3304, 1558],
 [1136, 2394, 3787, 2719, 2085, 2978],
 [4613, 2815, 2204, 1142, 2345, 2554, 3125, 3128, 1890],
 [1271, 1904, 2543, 1321, 4591, 3491, 294],
 [4579, 1716, 1302, 4237, 191, 214

### Embedding Representation

In [17]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4718 1271 3966]
 [   0    0    0 ... 3787  252 4440]
 [   0    0    0 ... 4967 3191  511]
 ...
 [   0    0    0 ... 1814 4607 1101]
 [   0    0    0 ... 1353 4727 1885]
 [   0    0    0 ...  984 3787 1792]]


In [18]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 4718, 1271, 3966])

In [19]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [21]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainabl

In [22]:
### Vocabulary size
voc_size=5000

In [23]:
messages=X.copy()

In [24]:
messages['title'][1]

'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)'

In [25]:
messages.reset_index(inplace=True)

In [26]:
import nltk
import re
from nltk.corpus import stopwords

In [27]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070


3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732


5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394


In [28]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [29]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4718, 1271, 3966],
 [559, 964, 4841, 4110, 2270, 2260, 2382, 2669, 3787, 252, 4440],
 [1414, 3535, 4967, 3191, 511],
 [3747, 1628, 4823, 3505, 3922, 2345, 3621, 2478],
 [2343, 4579, 3668, 1806, 1792],
 [94, 1740],
 [2250, 1286, 559, 1819, 4602, 4479],
 [1506, 632, 3779],
 [4616, 2713, 3787, 1904, 4340, 265, 885],
 [3552, 3442, 2543, 4579, 3490, 48, 975, 1355, 7],
 [2104, 1904, 2598, 4664, 4241, 1565, 1271, 1904, 4371],
 [3824, 3787, 3600, 3774, 2178, 2340, 2925, 2439, 878, 3194],
 [624, 86, 1016, 2064, 2628, 1756, 1691, 2972, 4440],
 [18, 1558, 3278, 4570, 4983],
 [3787, 194, 4317, 2728],
 [2808, 4535, 4957],
 [4480, 235, 2618, 1271, 1567, 556, 3391, 3896, 3330],
 [1271, 1904, 2207, 1539, 1558, 2063, 2938, 3140, 3398, 418, 4559, 1756, 1691],
 [3552, 1980, 2618, 2284],
 [4660, 2719, 2610, 1183, 2067, 3304, 1558],
 [1136, 2394, 3787, 2719, 2085, 2978],
 [4613, 2815, 2204, 1142, 2345, 2554, 3125, 3128, 1890],
 [1271, 1904, 2543, 1321, 4591, 3491, 294],
 [4579, 1716, 1302, 4237, 191, 214

In [30]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4718 1271 3966]
 [   0    0    0 ... 3787  252 4440]
 [   0    0    0 ... 4967 3191  511]
 ...
 [   0    0    0 ... 1814 4607 1101]
 [   0    0    0 ... 1353 4727 1885]
 [   0    0    0 ...  984 3787 1792]]


In [31]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 4718, 1271, 3966])

In [32]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
len(embedded_docs),y.shape

(6335, (6335,))

In [34]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [35]:
X_final.shape,y_final.shape

((6335, 20), (6335,))

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [37]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Train on 4244 samples, validate on 2091 samples
Epoch 1/10
4244/4244 [==============================] - 4s 1ms/sample - loss: 0.6556 - acc: 0.6060 - val_loss: 0.4791 - val_acc: 0.7690
Epoch 2/10
4244/4244 [==============================] - 3s 685us/sample - loss: 0.3635 - acc: 0.8414 - val_loss: 0.4750 - val_acc: 0.7762
Epoch 3/10
4244/4244 [==============================] - 3s 701us/sample - loss: 0.2276 - acc: 0.9121 - val_loss: 0.5820 - val_acc: 0.7695
Epoch 4/10
4244/4244 [==============================] - 3s 750us/sample - loss: 0.1562 - acc: 0.9444 - val_loss: 0.6450 - val_acc: 0.7623
Epoch 5/10
4244/4244 [==============================] - 3s 761us/sample - loss: 0.1211 - acc: 0.9588 - val_loss: 0.7796 - val_acc: 0.7504
Epoch 6/10
4244/4244 [==============================] - 3s 764us/sample - loss: 0.0919 - acc: 0.9713 - val_loss: 0.9257 - val_acc: 0.7504
Epoch 7/10
4244/4244 [==============================] - 3s 755us/sample - loss: 0.0659 - acc: 0.9790 - val_loss: 0.9624 - val_

In [38]:
y_pred1=model1.predict_classes(X_test)

In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred1)

array([[816, 255],
       [276, 744]], dtype=int64)

In [40]:
confusion_matrix(y_test,y_pred1)

array([[816, 255],
       [276, 744]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.7460545193687231

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.75      0.76      0.75      1071
           1       0.74      0.73      0.74      1020

    accuracy                           0.75      2091
   macro avg       0.75      0.75      0.75      2091
weighted avg       0.75      0.75      0.75      2091

